/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaracteristicasRouteImport } from './routes/caracteristicas'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemostracionRouteImport } from './routes/demostracion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DemoAgendaRouteImport } from './routes/demo_.agenda'
import { Route as DemoComunicacionesRouteImport } from './routes/demo_.comunicaciones'
import { Route as DemoEquipoProfesionalRouteImport } from './routes/demo_.equipo-profesional'
import { Route as DemoEstudiosRouteImport } from './routes/demo_.estudios'
import { Route as DemoHistoriaRouteImport } from './routes/demo_.historia'
import { Route as DemoMarketingRouteImport } from './routes/demo_.marketing'
import { Route as DemoNotificacionesRouteImport } from './routes/demo_.notificaciones'
import { Route as DemoOdontogramaRouteImport } from './routes/demo_.odontograma'
import { Route as DemoOdontograma3dRouteImport } from './routes/demo_.odontograma-3d'
import { Route as DemoPacientesRouteImport } from './routes/demo_.pacientes'
import { Route as DemoPortalPacienteRouteImport } from './routes/demo_.portal-paciente'
import { Route as DemoPresupuestosRouteImport } from './routes/demo_.presupuestos'
import { Route as DemoRecetasRouteImport } from './routes/demo_.recetas'
import { Route as DemoTratamientosRouteImport } from './routes/demo_.tratamientos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaracteristicasRoute = CaracteristicasRouteImport.update({
  id: '/caracteristicas',
  path: '/caracteristicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DemostracionRoute = DemostracionRouteImport.update({
  id: '/demostracion',
  path: '/demostracion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/demo_/agenda',
  path: '/demo/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComunicacionesRoute = DemoComunicacionesRouteImport.update({
  id: '/demo_/comunicaciones',
  path: '/demo/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEquipoProfesionalRoute = DemoEquipoProfesionalRouteImport.update({
  id: '/demo_/equipo-profesional',
  path: '/demo/equipo-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEstudiosRoute = DemoEstudiosRouteImport.update({
  id: '/demo_/estudios',
  path: '/demo/estudios',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHistoriaRoute = DemoHistoriaRouteImport.update({
  id: '/demo_/historia',
  path: '/demo/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMarketingRoute = DemoMarketingRouteImport.update({
  id: '/demo_/marketing',
  path: '/demo/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNotificacionesRoute = DemoNotificacionesRouteImport.update({
  id: '/demo_/notificaciones',
  path: '/demo/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOdontogramaRoute = DemoOdontogramaRouteImport.update({
  id: '/demo_/odontograma',
  path: '/demo/odontograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOdontograma3dRoute = DemoOdontograma3dRouteImport.update({
  id: '/demo_/odontograma-3d',
  path: '/demo/odontograma-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPacientesRoute = DemoPacientesRouteImport.update({
  id: '/demo_/pacientes',
  path: '/demo/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPortalPacienteRoute = DemoPortalPacienteRouteImport.update({
  id: '/demo_/portal-paciente',
  path: '/demo/portal-paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPresupuestosRoute = DemoPresupuestosRouteImport.update({
  id: '/demo_/presupuestos',
  path: '/demo/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRecetasRoute = DemoRecetasRouteImport.update({
  id: '/demo_/recetas',
  path: '/demo/recetas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTratamientosRoute = DemoTratamientosRouteImport.update({
  id: '/demo_/tratamientos',
  path: '/demo/tratamientos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/comunicaciones': typeof DemoComunicacionesRoute
  '/demo/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo/estudios': typeof DemoEstudiosRoute
  '/demo/historia': typeof DemoHistoriaRoute
  '/demo/marketing': typeof DemoMarketingRoute
  '/demo/notificaciones': typeof DemoNotificacionesRoute
  '/demo/odontograma': typeof DemoOdontogramaRoute
  '/demo/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo/pacientes': typeof DemoPacientesRoute
  '/demo/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo/presupuestos': typeof DemoPresupuestosRoute
  '/demo/recetas': typeof DemoRecetasRoute
  '/demo/tratamientos': typeof DemoTratamientosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/comunicaciones': typeof DemoComunicacionesRoute
  '/demo/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo/estudios': typeof DemoEstudiosRoute
  '/demo/historia': typeof DemoHistoriaRoute
  '/demo/marketing': typeof DemoMarketingRoute
  '/demo/notificaciones': typeof DemoNotificacionesRoute
  '/demo/odontograma': typeof DemoOdontogramaRoute
  '/demo/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo/pacientes': typeof DemoPacientesRoute
  '/demo/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo/presupuestos': typeof DemoPresupuestosRoute
  '/demo/recetas': typeof DemoRecetasRoute
  '/demo/tratamientos': typeof DemoTratamientosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/demo_/agenda': typeof DemoAgendaRoute
  '/demo_/comunicaciones': typeof DemoComunicacionesRoute
  '/demo_/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo_/estudios': typeof DemoEstudiosRoute
  '/demo_/historia': typeof DemoHistoriaRoute
  '/demo_/marketing': typeof DemoMarketingRoute
  '/demo_/notificaciones': typeof DemoNotificacionesRoute
  '/demo_/odontograma': typeof DemoOdontogramaRoute
  '/demo_/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo_/pacientes': typeof DemoPacientesRoute
  '/demo_/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo_/presupuestos': typeof DemoPresupuestosRoute
  '/demo_/recetas': typeof DemoRecetasRoute
  '/demo_/tratamientos': typeof DemoTratamientosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/demo/agenda'
    | '/demo/comunicaciones'
    | '/demo/equipo-profesional'
    | '/demo/estudios'
    | '/demo/historia'
    | '/demo/marketing'
    | '/demo/notificaciones'
    | '/demo/odontograma'
    | '/demo/odontograma-3d'
    | '/demo/pacientes'
    | '/demo/portal-paciente'
    | '/demo/presupuestos'
    | '/demo/recetas'
    | '/demo/tratamientos'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/demo/agenda'
    | '/demo/comunicaciones'
    | '/demo/equipo-profesional'
    | '/demo/estudios'
    | '/demo/historia'
    | '/demo/marketing'
    | '/demo/notificaciones'
    | '/demo/odontograma'
    | '/demo/odontograma-3d'
    | '/demo/pacientes'
    | '/demo/portal-paciente'
    | '/demo/presupuestos'
    | '/demo/recetas'
    | '/demo/tratamientos'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/demo_/agenda'
    | '/demo_/comunicaciones'
    | '/demo_/equipo-profesional'
    | '/demo_/estudios'
    | '/demo_/historia'
    | '/demo_/marketing'
    | '/demo_/notificaciones'
    | '/demo_/odontograma'
    | '/demo_/odontograma-3d'
    | '/demo_/pacientes'
    | '/demo_/portal-paciente'
    | '/demo_/presupuestos'
    | '/demo_/recetas'
    | '/demo_/tratamientos'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaracteristicasRoute: typeof CaracteristicasRoute
  DemoRoute: typeof DemoRoute
  DemostracionRoute: typeof DemostracionRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  PlanesRoute: typeof PlanesRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  RegistroRoute: typeof RegistroRoute
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoComunicacionesRoute: typeof DemoComunicacionesRoute
  DemoEquipoProfesionalRoute: typeof DemoEquipoProfesionalRoute
  DemoEstudiosRoute: typeof DemoEstudiosRoute
  DemoHistoriaRoute: typeof DemoHistoriaRoute
  DemoMarketingRoute: typeof DemoMarketingRoute
  DemoNotificacionesRoute: typeof DemoNotificacionesRoute
  DemoOdontogramaRoute: typeof DemoOdontogramaRoute
  DemoOdontograma3dRoute: typeof DemoOdontograma3dRoute
  DemoPacientesRoute: typeof DemoPacientesRoute
  DemoPortalPacienteRoute: typeof DemoPortalPacienteRoute
  DemoPresupuestosRoute: typeof DemoPresupuestosRoute
  DemoRecetasRoute: typeof DemoRecetasRoute
  DemoTratamientosRoute: typeof DemoTratamientosRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caracteristicas': {
      id: '/caracteristicas'
      path: '/caracteristicas'
      fullPath: '/caracteristicas'
      preLoaderRoute: typeof CaracteristicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demostracion': {
      id: '/demostracion'
      path: '/demostracion'
      fullPath: '/demostracion'
      preLoaderRoute: typeof DemostracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/agenda': {
      id: '/demo_/agenda'
      path: '/demo/agenda'
      fullPath: '/demo/agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/comunicaciones': {
      id: '/demo_/comunicaciones'
      path: '/demo/comunicaciones'
      fullPath: '/demo/comunicaciones'
      preLoaderRoute: typeof DemoComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/equipo-profesional': {
      id: '/demo_/equipo-profesional'
      path: '/demo/equipo-profesional'
      fullPath: '/demo/equipo-profesional'
      preLoaderRoute: typeof DemoEquipoProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/estudios': {
      id: '/demo_/estudios'
      path: '/demo/estudios'
      fullPath: '/demo/estudios'
      preLoaderRoute: typeof DemoEstudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/historia': {
      id: '/demo_/historia'
      path: '/demo/historia'
      fullPath: '/demo/historia'
      preLoaderRoute: typeof DemoHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/marketing': {
      id: '/demo_/marketing'
      path: '/demo/marketing'
      fullPath: '/demo/marketing'
      preLoaderRoute: typeof DemoMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/notificaciones': {
      id: '/demo_/notificaciones'
      path: '/demo/notificaciones'
      fullPath: '/demo/notificaciones'
      preLoaderRoute: typeof DemoNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/odontograma': {
      id: '/demo_/odontograma'
      path: '/demo/odontograma'
      fullPath: '/demo/odontograma'
      preLoaderRoute: typeof DemoOdontogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/odontograma-3d': {
      id: '/demo_/odontograma-3d'
      path: '/demo/odontograma-3d'
      fullPath: '/demo/odontograma-3d'
      preLoaderRoute: typeof DemoOdontograma3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/pacientes': {
      id: '/demo_/pacientes'
      path: '/demo/pacientes'
      fullPath: '/demo/pacientes'
      preLoaderRoute: typeof DemoPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/portal-paciente': {
      id: '/demo_/portal-paciente'
      path: '/demo/portal-paciente'
      fullPath: '/demo/portal-paciente'
      preLoaderRoute: typeof DemoPortalPacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/presupuestos': {
      id: '/demo_/presupuestos'
      path: '/demo/presupuestos'
      fullPath: '/demo/presupuestos'
      preLoaderRoute: typeof DemoPresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/recetas': {
      id: '/demo_/recetas'
      path: '/demo/recetas'
      fullPath: '/demo/recetas'
      preLoaderRoute: typeof DemoRecetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/tratamientos': {
      id: '/demo_/tratamientos'
      path: '/demo/tratamientos'
      fullPath: '/demo/tratamientos'
      preLoaderRoute: typeof DemoTratamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaracteristicasRoute: CaracteristicasRoute,
  DemoRoute: DemoRoute,
  DemostracionRoute: DemostracionRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  PlanesRoute: PlanesRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  RegistroRoute: RegistroRoute,
  DemoAgendaRoute: DemoAgendaRoute,
  DemoComunicacionesRoute: DemoComunicacionesRoute,
  DemoEquipoProfesionalRoute: DemoEquipoProfesionalRoute,
  DemoEstudiosRoute: DemoEstudiosRoute,
  DemoHistoriaRoute: DemoHistoriaRoute,
  DemoMarketingRoute: DemoMarketingRoute,
  DemoNotificacionesRoute: DemoNotificacionesRoute,
  DemoOdontogramaRoute: DemoOdontogramaRoute,
  DemoOdontograma3dRoute: DemoOdontograma3dRoute,
  DemoPacientesRoute: DemoPacientesRoute,
  DemoPortalPacienteRoute: DemoPortalPacienteRoute,
  DemoPresupuestosRoute: DemoPresupuestosRoute,
  DemoRecetasRoute: DemoRecetasRoute,
  DemoTratamientosRoute: DemoTratamientosRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
