/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoPruebaRouteImport } from './routes/acceso-prueba'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CaracteristicasRouteImport } from './routes/caracteristicas'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DemostracionRouteImport } from './routes/demostracion'
import { Route as DuenoRouteImport } from './routes/dueno'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as FormularioRouteImport } from './routes/formulario'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccesosRouteImport } from './routes/admin.accesos'
import { Route as AdminActividadRouteImport } from './routes/admin.actividad'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminClinicasRouteImport } from './routes/admin.clinicas'
import { Route as AdminCuentaRouteImport } from './routes/admin.cuenta'
import { Route as AdminDemosRouteImport } from './routes/admin.demos'
import { Route as AdminGastosRouteImport } from './routes/admin.gastos'
import { Route as AdminIaRouteImport } from './routes/admin.ia'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNominaRouteImport } from './routes/admin.nomina'
import { Route as AdminNotificacionesRouteImport } from './routes/admin.notificaciones'
import { Route as AdminPagosRouteImport } from './routes/admin.pagos'
import { Route as AdminPaisesRouteImport } from './routes/admin.paises'
import { Route as AdminPersonalRouteImport } from './routes/admin.personal'
import { Route as AdminPlanesRouteImport } from './routes/admin.planes'
import { Route as AdminRecuperarRouteImport } from './routes/admin.recuperar'
import { Route as AdminReportesRouteImport } from './routes/admin.reportes'
import { Route as AdminRestablecerRouteImport } from './routes/admin.restablecer'
import { Route as AdminSoporteRouteImport } from './routes/admin.soporte'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DemoAdminRouteImport } from './routes/demo_.admin'
import { Route as DemoAgendaRouteImport } from './routes/demo_.agenda'
import { Route as DemoAutomatizacionesRouteImport } from './routes/demo_.automatizaciones'
import { Route as DemoBiRouteImport } from './routes/demo_.bi'
import { Route as DemoComunicacionesRouteImport } from './routes/demo_.comunicaciones'
import { Route as DemoConfiguracionRouteImport } from './routes/demo_.configuracion'
import { Route as DemoEquipoProfesionalRouteImport } from './routes/demo_.equipo-profesional'
import { Route as DemoEstudiosRouteImport } from './routes/demo_.estudios'
import { Route as DemoFacturacionRouteImport } from './routes/demo_.facturacion'
import { Route as DemoFinanzasRouteImport } from './routes/demo_.finanzas'
import { Route as DemoHistoriaRouteImport } from './routes/demo_.historia'
import { Route as DemoIaRouteImport } from './routes/demo_.ia'
import { Route as DemoIntegracionesRouteImport } from './routes/demo_.integraciones'
import { Route as DemoInventarioRouteImport } from './routes/demo_.inventario'
import { Route as DemoLaboratorioRouteImport } from './routes/demo_.laboratorio'
import { Route as DemoMarketingRouteImport } from './routes/demo_.marketing'
import { Route as DemoMultiempresaRouteImport } from './routes/demo_.multiempresa'
import { Route as DemoNotificacionesRouteImport } from './routes/demo_.notificaciones'
import { Route as DemoOdontogramaRouteImport } from './routes/demo_.odontograma'
import { Route as DemoOdontograma3dRouteImport } from './routes/demo_.odontograma-3d'
import { Route as DemoPacientesRouteImport } from './routes/demo_.pacientes'
import { Route as DemoPortalPacienteRouteImport } from './routes/demo_.portal-paciente'
import { Route as DemoPresupuestosRouteImport } from './routes/demo_.presupuestos'
import { Route as DemoRecetasRouteImport } from './routes/demo_.recetas'
import { Route as DemoRrhhRouteImport } from './routes/demo_.rrhh'
import { Route as DemoTratamientosRouteImport } from './routes/demo_.tratamientos'
import { Route as DemoEquipoProfesionalAgendasHorariosRouteImport } from './routes/demo_.equipo-profesional_.agendas-horarios'
import { Route as DemoEquipoProfesionalEspecialidadesRouteImport } from './routes/demo_.equipo-profesional_.especialidades'
import { Route as DemoEquipoProfesionalPermisosAccesosRouteImport } from './routes/demo_.equipo-profesional_.permisos-accesos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoPruebaRoute = AccesoPruebaRouteImport.update({
  id: '/acceso-prueba',
  path: '/acceso-prueba',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaracteristicasRoute = CaracteristicasRouteImport.update({
  id: '/caracteristicas',
  path: '/caracteristicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/demo.lazy').then((d) => d.Route))
const DemostracionRoute = DemostracionRouteImport.update({
  id: '/demostracion',
  path: '/demostracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DuenoRoute = DuenoRouteImport.update({
  id: '/dueno',
  path: '/dueno',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioRoute = FormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccesosRoute = AdminAccesosRouteImport.update({
  id: '/accesos',
  path: '/accesos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActividadRoute = AdminActividadRouteImport.update({
  id: '/actividad',
  path: '/actividad',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicasRoute = AdminClinicasRouteImport.update({
  id: '/clinicas',
  path: '/clinicas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentaRoute = AdminCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemosRoute = AdminDemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGastosRoute = AdminGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNominaRoute = AdminNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaisesRoute = AdminPaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPersonalRoute = AdminPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecuperarRoute = AdminRecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestablecerRoute = AdminRestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSoporteRoute = AdminSoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAdminRoute = DemoAdminRouteImport.update({
  id: '/demo_/admin',
  path: '/demo/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAgendaRoute = DemoAgendaRouteImport.update({
  id: '/demo_/agenda',
  path: '/demo/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoAutomatizacionesRoute = DemoAutomatizacionesRouteImport.update({
  id: '/demo_/automatizaciones',
  path: '/demo/automatizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBiRoute = DemoBiRouteImport.update({
  id: '/demo_/bi',
  path: '/demo/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoComunicacionesRoute = DemoComunicacionesRouteImport.update({
  id: '/demo_/comunicaciones',
  path: '/demo/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConfiguracionRoute = DemoConfiguracionRouteImport.update({
  id: '/demo_/configuracion',
  path: '/demo/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEquipoProfesionalRoute = DemoEquipoProfesionalRouteImport.update({
  id: '/demo_/equipo-profesional',
  path: '/demo/equipo-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEstudiosRoute = DemoEstudiosRouteImport.update({
  id: '/demo_/estudios',
  path: '/demo/estudios',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFacturacionRoute = DemoFacturacionRouteImport.update({
  id: '/demo_/facturacion',
  path: '/demo/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFinanzasRoute = DemoFinanzasRouteImport.update({
  id: '/demo_/finanzas',
  path: '/demo/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHistoriaRoute = DemoHistoriaRouteImport.update({
  id: '/demo_/historia',
  path: '/demo/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIaRoute = DemoIaRouteImport.update({
  id: '/demo_/ia',
  path: '/demo/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIntegracionesRoute = DemoIntegracionesRouteImport.update({
  id: '/demo_/integraciones',
  path: '/demo/integraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInventarioRoute = DemoInventarioRouteImport.update({
  id: '/demo_/inventario',
  path: '/demo/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLaboratorioRoute = DemoLaboratorioRouteImport.update({
  id: '/demo_/laboratorio',
  path: '/demo/laboratorio',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMarketingRoute = DemoMarketingRouteImport.update({
  id: '/demo_/marketing',
  path: '/demo/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMultiempresaRoute = DemoMultiempresaRouteImport.update({
  id: '/demo_/multiempresa',
  path: '/demo/multiempresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNotificacionesRoute = DemoNotificacionesRouteImport.update({
  id: '/demo_/notificaciones',
  path: '/demo/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOdontogramaRoute = DemoOdontogramaRouteImport.update({
  id: '/demo_/odontograma',
  path: '/demo/odontograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOdontograma3dRoute = DemoOdontograma3dRouteImport.update({
  id: '/demo_/odontograma-3d',
  path: '/demo/odontograma-3d',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPacientesRoute = DemoPacientesRouteImport.update({
  id: '/demo_/pacientes',
  path: '/demo/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPortalPacienteRoute = DemoPortalPacienteRouteImport.update({
  id: '/demo_/portal-paciente',
  path: '/demo/portal-paciente',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPresupuestosRoute = DemoPresupuestosRouteImport.update({
  id: '/demo_/presupuestos',
  path: '/demo/presupuestos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRecetasRoute = DemoRecetasRouteImport.update({
  id: '/demo_/recetas',
  path: '/demo/recetas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRrhhRoute = DemoRrhhRouteImport.update({
  id: '/demo_/rrhh',
  path: '/demo/rrhh',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTratamientosRoute = DemoTratamientosRouteImport.update({
  id: '/demo_/tratamientos',
  path: '/demo/tratamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEquipoProfesionalAgendasHorariosRoute =
  DemoEquipoProfesionalAgendasHorariosRouteImport.update({
    id: '/demo_/equipo-profesional_/agendas-horarios',
    path: '/demo/equipo-profesional/agendas-horarios',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoEquipoProfesionalEspecialidadesRoute =
  DemoEquipoProfesionalEspecialidadesRouteImport.update({
    id: '/demo_/equipo-profesional_/especialidades',
    path: '/demo/equipo-profesional/especialidades',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoEquipoProfesionalPermisosAccesosRoute =
  DemoEquipoProfesionalPermisosAccesosRouteImport.update({
    id: '/demo_/equipo-profesional_/permisos-accesos',
    path: '/demo/equipo-profesional/permisos-accesos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso-prueba': typeof AccesoPruebaRoute
  '/admin': typeof AdminRouteWithChildren
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/dueno': typeof DuenoRoute
  '/equipo': typeof EquipoRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nomina': typeof AdminNominaRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/paises': typeof AdminPaisesRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/restablecer': typeof AdminRestablecerRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/automatizaciones': typeof DemoAutomatizacionesRoute
  '/demo/bi': typeof DemoBiRoute
  '/demo/comunicaciones': typeof DemoComunicacionesRoute
  '/demo/configuracion': typeof DemoConfiguracionRoute
  '/demo/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo/estudios': typeof DemoEstudiosRoute
  '/demo/facturacion': typeof DemoFacturacionRoute
  '/demo/finanzas': typeof DemoFinanzasRoute
  '/demo/historia': typeof DemoHistoriaRoute
  '/demo/ia': typeof DemoIaRoute
  '/demo/integraciones': typeof DemoIntegracionesRoute
  '/demo/inventario': typeof DemoInventarioRoute
  '/demo/laboratorio': typeof DemoLaboratorioRoute
  '/demo/marketing': typeof DemoMarketingRoute
  '/demo/multiempresa': typeof DemoMultiempresaRoute
  '/demo/notificaciones': typeof DemoNotificacionesRoute
  '/demo/odontograma': typeof DemoOdontogramaRoute
  '/demo/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo/pacientes': typeof DemoPacientesRoute
  '/demo/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo/presupuestos': typeof DemoPresupuestosRoute
  '/demo/recetas': typeof DemoRecetasRoute
  '/demo/rrhh': typeof DemoRrhhRoute
  '/demo/tratamientos': typeof DemoTratamientosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/demo/equipo-profesional/agendas-horarios': typeof DemoEquipoProfesionalAgendasHorariosRoute
  '/demo/equipo-profesional/especialidades': typeof DemoEquipoProfesionalEspecialidadesRoute
  '/demo/equipo-profesional/permisos-accesos': typeof DemoEquipoProfesionalPermisosAccesosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso-prueba': typeof AccesoPruebaRoute
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/dueno': typeof DuenoRoute
  '/equipo': typeof EquipoRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nomina': typeof AdminNominaRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/paises': typeof AdminPaisesRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/restablecer': typeof AdminRestablecerRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/demo/admin': typeof DemoAdminRoute
  '/demo/agenda': typeof DemoAgendaRoute
  '/demo/automatizaciones': typeof DemoAutomatizacionesRoute
  '/demo/bi': typeof DemoBiRoute
  '/demo/comunicaciones': typeof DemoComunicacionesRoute
  '/demo/configuracion': typeof DemoConfiguracionRoute
  '/demo/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo/estudios': typeof DemoEstudiosRoute
  '/demo/facturacion': typeof DemoFacturacionRoute
  '/demo/finanzas': typeof DemoFinanzasRoute
  '/demo/historia': typeof DemoHistoriaRoute
  '/demo/ia': typeof DemoIaRoute
  '/demo/integraciones': typeof DemoIntegracionesRoute
  '/demo/inventario': typeof DemoInventarioRoute
  '/demo/laboratorio': typeof DemoLaboratorioRoute
  '/demo/marketing': typeof DemoMarketingRoute
  '/demo/multiempresa': typeof DemoMultiempresaRoute
  '/demo/notificaciones': typeof DemoNotificacionesRoute
  '/demo/odontograma': typeof DemoOdontogramaRoute
  '/demo/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo/pacientes': typeof DemoPacientesRoute
  '/demo/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo/presupuestos': typeof DemoPresupuestosRoute
  '/demo/recetas': typeof DemoRecetasRoute
  '/demo/rrhh': typeof DemoRrhhRoute
  '/demo/tratamientos': typeof DemoTratamientosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/demo/equipo-profesional/agendas-horarios': typeof DemoEquipoProfesionalAgendasHorariosRoute
  '/demo/equipo-profesional/especialidades': typeof DemoEquipoProfesionalEspecialidadesRoute
  '/demo/equipo-profesional/permisos-accesos': typeof DemoEquipoProfesionalPermisosAccesosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso-prueba': typeof AccesoPruebaRoute
  '/admin': typeof AdminRouteWithChildren
  '/caracteristicas': typeof CaracteristicasRoute
  '/demo': typeof DemoRoute
  '/demostracion': typeof DemostracionRoute
  '/dueno': typeof DuenoRoute
  '/equipo': typeof EquipoRoute
  '/formulario': typeof FormularioRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/planes': typeof PlanesRoute
  '/portal': typeof PortalRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/registro': typeof RegistroRoute
  '/admin/accesos': typeof AdminAccesosRoute
  '/admin/actividad': typeof AdminActividadRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/clinicas': typeof AdminClinicasRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/demos': typeof AdminDemosRoute
  '/admin/gastos': typeof AdminGastosRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/nomina': typeof AdminNominaRoute
  '/admin/notificaciones': typeof AdminNotificacionesRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/admin/paises': typeof AdminPaisesRoute
  '/admin/personal': typeof AdminPersonalRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/recuperar': typeof AdminRecuperarRoute
  '/admin/reportes': typeof AdminReportesRoute
  '/admin/restablecer': typeof AdminRestablecerRoute
  '/admin/soporte': typeof AdminSoporteRoute
  '/demo_/admin': typeof DemoAdminRoute
  '/demo_/agenda': typeof DemoAgendaRoute
  '/demo_/automatizaciones': typeof DemoAutomatizacionesRoute
  '/demo_/bi': typeof DemoBiRoute
  '/demo_/comunicaciones': typeof DemoComunicacionesRoute
  '/demo_/configuracion': typeof DemoConfiguracionRoute
  '/demo_/equipo-profesional': typeof DemoEquipoProfesionalRoute
  '/demo_/estudios': typeof DemoEstudiosRoute
  '/demo_/facturacion': typeof DemoFacturacionRoute
  '/demo_/finanzas': typeof DemoFinanzasRoute
  '/demo_/historia': typeof DemoHistoriaRoute
  '/demo_/ia': typeof DemoIaRoute
  '/demo_/integraciones': typeof DemoIntegracionesRoute
  '/demo_/inventario': typeof DemoInventarioRoute
  '/demo_/laboratorio': typeof DemoLaboratorioRoute
  '/demo_/marketing': typeof DemoMarketingRoute
  '/demo_/multiempresa': typeof DemoMultiempresaRoute
  '/demo_/notificaciones': typeof DemoNotificacionesRoute
  '/demo_/odontograma': typeof DemoOdontogramaRoute
  '/demo_/odontograma-3d': typeof DemoOdontograma3dRoute
  '/demo_/pacientes': typeof DemoPacientesRoute
  '/demo_/portal-paciente': typeof DemoPortalPacienteRoute
  '/demo_/presupuestos': typeof DemoPresupuestosRoute
  '/demo_/recetas': typeof DemoRecetasRoute
  '/demo_/rrhh': typeof DemoRrhhRoute
  '/demo_/tratamientos': typeof DemoTratamientosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/demo_/equipo-profesional_/agendas-horarios': typeof DemoEquipoProfesionalAgendasHorariosRoute
  '/demo_/equipo-profesional_/especialidades': typeof DemoEquipoProfesionalEspecialidadesRoute
  '/demo_/equipo-profesional_/permisos-accesos': typeof DemoEquipoProfesionalPermisosAccesosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso-prueba'
    | '/admin'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/dueno'
    | '/equipo'
    | '/formulario'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/portal'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/auditoria'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/demos'
    | '/admin/gastos'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/nomina'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/admin/paises'
    | '/admin/personal'
    | '/admin/planes'
    | '/admin/recuperar'
    | '/admin/reportes'
    | '/admin/restablecer'
    | '/admin/soporte'
    | '/demo/admin'
    | '/demo/agenda'
    | '/demo/automatizaciones'
    | '/demo/bi'
    | '/demo/comunicaciones'
    | '/demo/configuracion'
    | '/demo/equipo-profesional'
    | '/demo/estudios'
    | '/demo/facturacion'
    | '/demo/finanzas'
    | '/demo/historia'
    | '/demo/ia'
    | '/demo/integraciones'
    | '/demo/inventario'
    | '/demo/laboratorio'
    | '/demo/marketing'
    | '/demo/multiempresa'
    | '/demo/notificaciones'
    | '/demo/odontograma'
    | '/demo/odontograma-3d'
    | '/demo/pacientes'
    | '/demo/portal-paciente'
    | '/demo/presupuestos'
    | '/demo/recetas'
    | '/demo/rrhh'
    | '/demo/tratamientos'
    | '/admin/'
    | '/app/'
    | '/demo/equipo-profesional/agendas-horarios'
    | '/demo/equipo-profesional/especialidades'
    | '/demo/equipo-profesional/permisos-accesos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso-prueba'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/dueno'
    | '/equipo'
    | '/formulario'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/portal'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/auditoria'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/demos'
    | '/admin/gastos'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/nomina'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/admin/paises'
    | '/admin/personal'
    | '/admin/planes'
    | '/admin/recuperar'
    | '/admin/reportes'
    | '/admin/restablecer'
    | '/admin/soporte'
    | '/demo/admin'
    | '/demo/agenda'
    | '/demo/automatizaciones'
    | '/demo/bi'
    | '/demo/comunicaciones'
    | '/demo/configuracion'
    | '/demo/equipo-profesional'
    | '/demo/estudios'
    | '/demo/facturacion'
    | '/demo/finanzas'
    | '/demo/historia'
    | '/demo/ia'
    | '/demo/integraciones'
    | '/demo/inventario'
    | '/demo/laboratorio'
    | '/demo/marketing'
    | '/demo/multiempresa'
    | '/demo/notificaciones'
    | '/demo/odontograma'
    | '/demo/odontograma-3d'
    | '/demo/pacientes'
    | '/demo/portal-paciente'
    | '/demo/presupuestos'
    | '/demo/recetas'
    | '/demo/rrhh'
    | '/demo/tratamientos'
    | '/admin'
    | '/app'
    | '/demo/equipo-profesional/agendas-horarios'
    | '/demo/equipo-profesional/especialidades'
    | '/demo/equipo-profesional/permisos-accesos'
  id:
    | '__root__'
    | '/'
    | '/acceso-prueba'
    | '/admin'
    | '/caracteristicas'
    | '/demo'
    | '/demostracion'
    | '/dueno'
    | '/equipo'
    | '/formulario'
    | '/login'
    | '/nosotros'
    | '/planes'
    | '/portal'
    | '/preguntas-frecuentes'
    | '/registro'
    | '/admin/accesos'
    | '/admin/actividad'
    | '/admin/auditoria'
    | '/admin/clinicas'
    | '/admin/cuenta'
    | '/admin/demos'
    | '/admin/gastos'
    | '/admin/ia'
    | '/admin/login'
    | '/admin/nomina'
    | '/admin/notificaciones'
    | '/admin/pagos'
    | '/admin/paises'
    | '/admin/personal'
    | '/admin/planes'
    | '/admin/recuperar'
    | '/admin/reportes'
    | '/admin/restablecer'
    | '/admin/soporte'
    | '/demo_/admin'
    | '/demo_/agenda'
    | '/demo_/automatizaciones'
    | '/demo_/bi'
    | '/demo_/comunicaciones'
    | '/demo_/configuracion'
    | '/demo_/equipo-profesional'
    | '/demo_/estudios'
    | '/demo_/facturacion'
    | '/demo_/finanzas'
    | '/demo_/historia'
    | '/demo_/ia'
    | '/demo_/integraciones'
    | '/demo_/inventario'
    | '/demo_/laboratorio'
    | '/demo_/marketing'
    | '/demo_/multiempresa'
    | '/demo_/notificaciones'
    | '/demo_/odontograma'
    | '/demo_/odontograma-3d'
    | '/demo_/pacientes'
    | '/demo_/portal-paciente'
    | '/demo_/presupuestos'
    | '/demo_/recetas'
    | '/demo_/rrhh'
    | '/demo_/tratamientos'
    | '/admin/'
    | '/app/'
    | '/demo_/equipo-profesional_/agendas-horarios'
    | '/demo_/equipo-profesional_/especialidades'
    | '/demo_/equipo-profesional_/permisos-accesos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoPruebaRoute: typeof AccesoPruebaRoute
  AdminRoute: typeof AdminRouteWithChildren
  CaracteristicasRoute: typeof CaracteristicasRoute
  DemoRoute: typeof DemoRoute
  DemostracionRoute: typeof DemostracionRoute
  DuenoRoute: typeof DuenoRoute
  EquipoRoute: typeof EquipoRoute
  FormularioRoute: typeof FormularioRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  PlanesRoute: typeof PlanesRoute
  PortalRoute: typeof PortalRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  RegistroRoute: typeof RegistroRoute
  DemoAdminRoute: typeof DemoAdminRoute
  DemoAgendaRoute: typeof DemoAgendaRoute
  DemoAutomatizacionesRoute: typeof DemoAutomatizacionesRoute
  DemoBiRoute: typeof DemoBiRoute
  DemoComunicacionesRoute: typeof DemoComunicacionesRoute
  DemoConfiguracionRoute: typeof DemoConfiguracionRoute
  DemoEquipoProfesionalRoute: typeof DemoEquipoProfesionalRoute
  DemoEstudiosRoute: typeof DemoEstudiosRoute
  DemoFacturacionRoute: typeof DemoFacturacionRoute
  DemoFinanzasRoute: typeof DemoFinanzasRoute
  DemoHistoriaRoute: typeof DemoHistoriaRoute
  DemoIaRoute: typeof DemoIaRoute
  DemoIntegracionesRoute: typeof DemoIntegracionesRoute
  DemoInventarioRoute: typeof DemoInventarioRoute
  DemoLaboratorioRoute: typeof DemoLaboratorioRoute
  DemoMarketingRoute: typeof DemoMarketingRoute
  DemoMultiempresaRoute: typeof DemoMultiempresaRoute
  DemoNotificacionesRoute: typeof DemoNotificacionesRoute
  DemoOdontogramaRoute: typeof DemoOdontogramaRoute
  DemoOdontograma3dRoute: typeof DemoOdontograma3dRoute
  DemoPacientesRoute: typeof DemoPacientesRoute
  DemoPortalPacienteRoute: typeof DemoPortalPacienteRoute
  DemoPresupuestosRoute: typeof DemoPresupuestosRoute
  DemoRecetasRoute: typeof DemoRecetasRoute
  DemoRrhhRoute: typeof DemoRrhhRoute
  DemoTratamientosRoute: typeof DemoTratamientosRoute
  AppIndexRoute: typeof AppIndexRoute
  DemoEquipoProfesionalAgendasHorariosRoute: typeof DemoEquipoProfesionalAgendasHorariosRoute
  DemoEquipoProfesionalEspecialidadesRoute: typeof DemoEquipoProfesionalEspecialidadesRoute
  DemoEquipoProfesionalPermisosAccesosRoute: typeof DemoEquipoProfesionalPermisosAccesosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso-prueba': {
      id: '/acceso-prueba'
      path: '/acceso-prueba'
      fullPath: '/acceso-prueba'
      preLoaderRoute: typeof AccesoPruebaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caracteristicas': {
      id: '/caracteristicas'
      path: '/caracteristicas'
      fullPath: '/caracteristicas'
      preLoaderRoute: typeof CaracteristicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demostracion': {
      id: '/demostracion'
      path: '/demostracion'
      fullPath: '/demostracion'
      preLoaderRoute: typeof DemostracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dueno': {
      id: '/dueno'
      path: '/dueno'
      fullPath: '/dueno'
      preLoaderRoute: typeof DuenoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario': {
      id: '/formulario'
      path: '/formulario'
      fullPath: '/formulario'
      preLoaderRoute: typeof FormularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accesos': {
      id: '/admin/accesos'
      path: '/accesos'
      fullPath: '/admin/accesos'
      preLoaderRoute: typeof AdminAccesosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actividad': {
      id: '/admin/actividad'
      path: '/actividad'
      fullPath: '/admin/actividad'
      preLoaderRoute: typeof AdminActividadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinicas': {
      id: '/admin/clinicas'
      path: '/clinicas'
      fullPath: '/admin/clinicas'
      preLoaderRoute: typeof AdminClinicasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuenta': {
      id: '/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AdminCuentaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demos': {
      id: '/admin/demos'
      path: '/demos'
      fullPath: '/admin/demos'
      preLoaderRoute: typeof AdminDemosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gastos': {
      id: '/admin/gastos'
      path: '/gastos'
      fullPath: '/admin/gastos'
      preLoaderRoute: typeof AdminGastosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nomina': {
      id: '/admin/nomina'
      path: '/nomina'
      fullPath: '/admin/nomina'
      preLoaderRoute: typeof AdminNominaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notificaciones': {
      id: '/admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/admin/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paises': {
      id: '/admin/paises'
      path: '/paises'
      fullPath: '/admin/paises'
      preLoaderRoute: typeof AdminPaisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/personal': {
      id: '/admin/personal'
      path: '/personal'
      fullPath: '/admin/personal'
      preLoaderRoute: typeof AdminPersonalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes': {
      id: '/admin/planes'
      path: '/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recuperar': {
      id: '/admin/recuperar'
      path: '/recuperar'
      fullPath: '/admin/recuperar'
      preLoaderRoute: typeof AdminRecuperarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reportes': {
      id: '/admin/reportes'
      path: '/reportes'
      fullPath: '/admin/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restablecer': {
      id: '/admin/restablecer'
      path: '/restablecer'
      fullPath: '/admin/restablecer'
      preLoaderRoute: typeof AdminRestablecerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/soporte': {
      id: '/admin/soporte'
      path: '/soporte'
      fullPath: '/admin/soporte'
      preLoaderRoute: typeof AdminSoporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/admin': {
      id: '/demo_/admin'
      path: '/demo/admin'
      fullPath: '/demo/admin'
      preLoaderRoute: typeof DemoAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/agenda': {
      id: '/demo_/agenda'
      path: '/demo/agenda'
      fullPath: '/demo/agenda'
      preLoaderRoute: typeof DemoAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/automatizaciones': {
      id: '/demo_/automatizaciones'
      path: '/demo/automatizaciones'
      fullPath: '/demo/automatizaciones'
      preLoaderRoute: typeof DemoAutomatizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/bi': {
      id: '/demo_/bi'
      path: '/demo/bi'
      fullPath: '/demo/bi'
      preLoaderRoute: typeof DemoBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/comunicaciones': {
      id: '/demo_/comunicaciones'
      path: '/demo/comunicaciones'
      fullPath: '/demo/comunicaciones'
      preLoaderRoute: typeof DemoComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/configuracion': {
      id: '/demo_/configuracion'
      path: '/demo/configuracion'
      fullPath: '/demo/configuracion'
      preLoaderRoute: typeof DemoConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/equipo-profesional': {
      id: '/demo_/equipo-profesional'
      path: '/demo/equipo-profesional'
      fullPath: '/demo/equipo-profesional'
      preLoaderRoute: typeof DemoEquipoProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/estudios': {
      id: '/demo_/estudios'
      path: '/demo/estudios'
      fullPath: '/demo/estudios'
      preLoaderRoute: typeof DemoEstudiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/facturacion': {
      id: '/demo_/facturacion'
      path: '/demo/facturacion'
      fullPath: '/demo/facturacion'
      preLoaderRoute: typeof DemoFacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/finanzas': {
      id: '/demo_/finanzas'
      path: '/demo/finanzas'
      fullPath: '/demo/finanzas'
      preLoaderRoute: typeof DemoFinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/historia': {
      id: '/demo_/historia'
      path: '/demo/historia'
      fullPath: '/demo/historia'
      preLoaderRoute: typeof DemoHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/ia': {
      id: '/demo_/ia'
      path: '/demo/ia'
      fullPath: '/demo/ia'
      preLoaderRoute: typeof DemoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/integraciones': {
      id: '/demo_/integraciones'
      path: '/demo/integraciones'
      fullPath: '/demo/integraciones'
      preLoaderRoute: typeof DemoIntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/inventario': {
      id: '/demo_/inventario'
      path: '/demo/inventario'
      fullPath: '/demo/inventario'
      preLoaderRoute: typeof DemoInventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/laboratorio': {
      id: '/demo_/laboratorio'
      path: '/demo/laboratorio'
      fullPath: '/demo/laboratorio'
      preLoaderRoute: typeof DemoLaboratorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/marketing': {
      id: '/demo_/marketing'
      path: '/demo/marketing'
      fullPath: '/demo/marketing'
      preLoaderRoute: typeof DemoMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/multiempresa': {
      id: '/demo_/multiempresa'
      path: '/demo/multiempresa'
      fullPath: '/demo/multiempresa'
      preLoaderRoute: typeof DemoMultiempresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/notificaciones': {
      id: '/demo_/notificaciones'
      path: '/demo/notificaciones'
      fullPath: '/demo/notificaciones'
      preLoaderRoute: typeof DemoNotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/odontograma': {
      id: '/demo_/odontograma'
      path: '/demo/odontograma'
      fullPath: '/demo/odontograma'
      preLoaderRoute: typeof DemoOdontogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/odontograma-3d': {
      id: '/demo_/odontograma-3d'
      path: '/demo/odontograma-3d'
      fullPath: '/demo/odontograma-3d'
      preLoaderRoute: typeof DemoOdontograma3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/pacientes': {
      id: '/demo_/pacientes'
      path: '/demo/pacientes'
      fullPath: '/demo/pacientes'
      preLoaderRoute: typeof DemoPacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/portal-paciente': {
      id: '/demo_/portal-paciente'
      path: '/demo/portal-paciente'
      fullPath: '/demo/portal-paciente'
      preLoaderRoute: typeof DemoPortalPacienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/presupuestos': {
      id: '/demo_/presupuestos'
      path: '/demo/presupuestos'
      fullPath: '/demo/presupuestos'
      preLoaderRoute: typeof DemoPresupuestosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/recetas': {
      id: '/demo_/recetas'
      path: '/demo/recetas'
      fullPath: '/demo/recetas'
      preLoaderRoute: typeof DemoRecetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/rrhh': {
      id: '/demo_/rrhh'
      path: '/demo/rrhh'
      fullPath: '/demo/rrhh'
      preLoaderRoute: typeof DemoRrhhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/tratamientos': {
      id: '/demo_/tratamientos'
      path: '/demo/tratamientos'
      fullPath: '/demo/tratamientos'
      preLoaderRoute: typeof DemoTratamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/equipo-profesional_/agendas-horarios': {
      id: '/demo_/equipo-profesional_/agendas-horarios'
      path: '/demo/equipo-profesional/agendas-horarios'
      fullPath: '/demo/equipo-profesional/agendas-horarios'
      preLoaderRoute: typeof DemoEquipoProfesionalAgendasHorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/equipo-profesional_/especialidades': {
      id: '/demo_/equipo-profesional_/especialidades'
      path: '/demo/equipo-profesional/especialidades'
      fullPath: '/demo/equipo-profesional/especialidades'
      preLoaderRoute: typeof DemoEquipoProfesionalEspecialidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo_/equipo-profesional_/permisos-accesos': {
      id: '/demo_/equipo-profesional_/permisos-accesos'
      path: '/demo/equipo-profesional/permisos-accesos'
      fullPath: '/demo/equipo-profesional/permisos-accesos'
      preLoaderRoute: typeof DemoEquipoProfesionalPermisosAccesosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccesosRoute: typeof AdminAccesosRoute
  AdminActividadRoute: typeof AdminActividadRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminClinicasRoute: typeof AdminClinicasRoute
  AdminCuentaRoute: typeof AdminCuentaRoute
  AdminDemosRoute: typeof AdminDemosRoute
  AdminGastosRoute: typeof AdminGastosRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNominaRoute: typeof AdminNominaRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminPaisesRoute: typeof AdminPaisesRoute
  AdminPersonalRoute: typeof AdminPersonalRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminRecuperarRoute: typeof AdminRecuperarRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminRestablecerRoute: typeof AdminRestablecerRoute
  AdminSoporteRoute: typeof AdminSoporteRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccesosRoute: AdminAccesosRoute,
  AdminActividadRoute: AdminActividadRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminClinicasRoute: AdminClinicasRoute,
  AdminCuentaRoute: AdminCuentaRoute,
  AdminDemosRoute: AdminDemosRoute,
  AdminGastosRoute: AdminGastosRoute,
  AdminIaRoute: AdminIaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNominaRoute: AdminNominaRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminPaisesRoute: AdminPaisesRoute,
  AdminPersonalRoute: AdminPersonalRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminRecuperarRoute: AdminRecuperarRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminRestablecerRoute: AdminRestablecerRoute,
  AdminSoporteRoute: AdminSoporteRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoPruebaRoute: AccesoPruebaRoute,
  AdminRoute: AdminRouteWithChildren,
  CaracteristicasRoute: CaracteristicasRoute,
  DemoRoute: DemoRoute,
  DemostracionRoute: DemostracionRoute,
  DuenoRoute: DuenoRoute,
  EquipoRoute: EquipoRoute,
  FormularioRoute: FormularioRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  PlanesRoute: PlanesRoute,
  PortalRoute: PortalRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  RegistroRoute: RegistroRoute,
  DemoAdminRoute: DemoAdminRoute,
  DemoAgendaRoute: DemoAgendaRoute,
  DemoAutomatizacionesRoute: DemoAutomatizacionesRoute,
  DemoBiRoute: DemoBiRoute,
  DemoComunicacionesRoute: DemoComunicacionesRoute,
  DemoConfiguracionRoute: DemoConfiguracionRoute,
  DemoEquipoProfesionalRoute: DemoEquipoProfesionalRoute,
  DemoEstudiosRoute: DemoEstudiosRoute,
  DemoFacturacionRoute: DemoFacturacionRoute,
  DemoFinanzasRoute: DemoFinanzasRoute,
  DemoHistoriaRoute: DemoHistoriaRoute,
  DemoIaRoute: DemoIaRoute,
  DemoIntegracionesRoute: DemoIntegracionesRoute,
  DemoInventarioRoute: DemoInventarioRoute,
  DemoLaboratorioRoute: DemoLaboratorioRoute,
  DemoMarketingRoute: DemoMarketingRoute,
  DemoMultiempresaRoute: DemoMultiempresaRoute,
  DemoNotificacionesRoute: DemoNotificacionesRoute,
  DemoOdontogramaRoute: DemoOdontogramaRoute,
  DemoOdontograma3dRoute: DemoOdontograma3dRoute,
  DemoPacientesRoute: DemoPacientesRoute,
  DemoPortalPacienteRoute: DemoPortalPacienteRoute,
  DemoPresupuestosRoute: DemoPresupuestosRoute,
  DemoRecetasRoute: DemoRecetasRoute,
  DemoRrhhRoute: DemoRrhhRoute,
  DemoTratamientosRoute: DemoTratamientosRoute,
  AppIndexRoute: AppIndexRoute,
  DemoEquipoProfesionalAgendasHorariosRoute:
    DemoEquipoProfesionalAgendasHorariosRoute,
  DemoEquipoProfesionalEspecialidadesRoute:
    DemoEquipoProfesionalEspecialidadesRoute,
  DemoEquipoProfesionalPermisosAccesosRoute:
    DemoEquipoProfesionalPermisosAccesosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
